name: Deployment Pipeline

on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/setup-node@v3

    - name: Set Up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install

    - name: Build Application
      run: npm run build

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test  

  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    needs: test
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Heroku CLI
      run: |
        curl https://cli-assets.heroku.com/install.sh | sh

    - name: Log in to Heroku
      run: heroku auth:token

    - name: Deploy to Heroku
      run: |
        git remote add heroku https://git.heroku.com/your-app-name.git
        git push heroku main  # Or specify the branch you want to deploy
