name: Fix Dependencies

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Remove node_modules and reinstall dependencies
        run: |
          rm -rf node_modules
          npm install
